#### Numpy Practice Exercise

Import Numpy

In [6]:
import numpy as np

Creating Array of 10 zeros

In [27]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create Array of 10 ones

In [9]:
array=np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Create Array of 6 twelves

In [14]:
array=np.array([6,6,6,6,6,6,6,6,6,6,6,6])
print(array)

[6 6 6 6 6 6 6 6 6 6 6 6]


Array of integers from 50 to 75

In [15]:
array=np.array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75])
print(array)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75]


Array of all the odd integers from 50 to 75


In [16]:
array=np.array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75])
print(array)

[51 53 55 57 59 61 63 65 67 69 71 73 75]


Create a 3x4 matrix with values ranging from 0 to 12

In [24]:
m= np.arange(0,12).reshape((3, 4))
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Create a 5x5 identity matrix

In [20]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [30]:
random = np.random.normal(0,1,1)
print(random)

[0.24817717]


Use NumPy to generate an array of 10 random numbers sampled from a standard normal distribution

In [31]:
random=np.random.normal(0,1,10)
print(random)

[-0.68534328  0.2594861   1.04113685  0.3140794  -0.62508636 -0.92601666
  0.46631568  0.15147453 -0.12943399  0.32923876]


Create the following matrix: 10x10 matrix from 1 to 100

In [35]:
m=np.arange(1,101).reshape(10,10)
print(m)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


Create the following matrix: ([[  10,   20,   30,   40,   50,   60,   70,   80,   90,  100],
       [ 110,  120,  130,  140,  150,  160,  170,  180,  190,  200],
       [ 210,  220,  230,  240,  250,  260,  270,  280,  290,  300],
       [ 310,  320,  330,  340,  350,  360,  370,  380,  390,  400],
       [ 410,  420,  430,  440,  450,  460,  470,  480,  490,  500],
       [ 510,  520,  530,  540,  550,  560,  570,  580,  590,  600],
       [ 610,  620,  630,  640,  650,  660,  670,  680,  690,  700],
       [ 710,  720,  730,  740,  750,  760,  770,  780,  790,  800],
       [ 810,  820,  830,  840,  850,  860,  870,  880,  890,  900],
       [ 910,  920,  930,  940,  950,  960,  970,  980,  990, 1000]])

In [83]:
m=np.arange(10,1010,10)
print(m)

[  10   20   30   40   50   60   70   80   90  100  110  120  130  140
  150  160  170  180  190  200  210  220  230  240  250  260  270  280
  290  300  310  320  330  340  350  360  370  380  390  400  410  420
  430  440  450  460  470  480  490  500  510  520  530  540  550  560
  570  580  590  600  610  620  630  640  650  660  670  680  690  700
  710  720  730  740  750  760  770  780  790  800  810  820  830  840
  850  860  870  880  890  900  910  920  930  940  950  960  970  980
  990 1000]


Create an array of 25 linearly spaced points between 0 and 1:

In [36]:
np.linspace(0,1,num=25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

**Numpy Indexing and Selection**

Make the Matrix 

In [42]:
m= np.arange(51,76).reshape((5, 5))
print(m)

[[51 52 53 54 55]
 [56 57 58 59 60]
 [61 62 63 64 65]
 [66 67 68 69 70]
 [71 72 73 74 75]]


Get matrices from created matrix

In [44]:
rows = m[2:5,:]
print(rows)

[[61 62 63 64 65]
 [66 67 68 69 70]
 [71 72 73 74 75]]


In [51]:
row= m[3][4]
print(row)

70


In [68]:
columns= m[0:3,1:2]
print(columns)

[[52]
 [57]
 [62]]


In [70]:
row_specific=m[4]
print(row_specific)

[71 72 73 74 75]


In [74]:
row_specific=m[3:5,:]
print(row_specific)

[[66 67 68 69 70]
 [71 72 73 74 75]]


**Perform the following operations**


Get the sum of all the values in the matrix

In [75]:
print(np.sum(m))

1575


Get the standard deviation of the values in matrix

In [76]:
print(np.std(m))

7.211102550927978



Get the sum of all the columns in matrix

In [77]:
print(np.sum(m,axis=0))

[305 310 315 320 325]


Get the sum of all the rows in matrix

In [78]:
print(np.sum(m, axis=1))

[265 290 315 340 365]
